import { Icells } from "../model";

export const cellsPM : Icells[] = [
  {selected: false,   day: "شن",   dayVal: "1",   hour: "20-21", hourVal: "20",     gridArea: "3/2/4/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "20-21", hourVal: "20",     gridArea: "3/3/4/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "20-21", hourVal: "20",     gridArea: "3/4/4/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "20-21", hourVal: "20",     gridArea: "3/5/4/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "20-21", hourVal: "20",     gridArea: "3/6/4/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "20-21", hourVal: "20",     gridArea: "3/7/4/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "20-21", hourVal: "20",     gridArea: "3/8/4/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "21-22", hourVal: "21",    gridArea: "4/2/5/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "21-22", hourVal: "21",    gridArea: "4/3/5/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "21-22", hourVal: "21",    gridArea: "4/4/5/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "21-22", hourVal: "21",    gridArea: "4/5/5/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "21-22", hourVal: "21",    gridArea: "4/6/5/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "21-22", hourVal: "21",    gridArea: "4/7/5/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "21-22", hourVal: "21",    gridArea: "4/8/5/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "22-23",  hourVal: "22",  gridArea: "5/2/6/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "22-23",  hourVal: "22",  gridArea: "5/3/6/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "22-23",  hourVal: "22",  gridArea: "5/4/6/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "22-23",  hourVal: "22",  gridArea: "5/5/6/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "22-23",  hourVal: "22",  gridArea: "5/6/6/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "22-23",  hourVal: "22",  gridArea: "5/7/6/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "22-23",  hourVal: "22",  gridArea: "5/8/6/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "23-24", hourVal: "23",   gridArea: "6/2/7/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "23-24", hourVal: "23",   gridArea: "6/3/7/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "23-24", hourVal: "23",   gridArea: "6/4/7/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "23-24", hourVal: "23",   gridArea: "6/5/7/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "23-24", hourVal: "23",   gridArea: "6/6/7/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "23-24", hourVal: "23",   gridArea: "6/7/7/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "23-24", hourVal: "23",   gridArea: "6/8/7/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "24-1", hourVal: "24",   gridArea: "7/2/8/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "24-1", hourVal: "24",   gridArea: "7/3/8/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "24-1", hourVal: "24",   gridArea: "7/4/8/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "24-1", hourVal: "24",   gridArea: "7/5/8/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "24-1", hourVal: "24",   gridArea: "7/6/8/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "24-1", hourVal: "24",   gridArea: "7/7/8/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "24-1", hourVal: "24",   gridArea: "7/8/8/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "1-2", hourVal: "1",   gridArea: "8/2/9/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "1-2", hourVal: "1",   gridArea: "8/3/9/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "1-2", hourVal: "1",   gridArea: "8/4/9/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "1-2", hourVal: "1",   gridArea: "8/5/9/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "1-2", hourVal: "1",   gridArea: "8/6/9/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "1-2", hourVal: "1",   gridArea: "8/7/9/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "1-2", hourVal: "1",   gridArea: "8/8/9/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "2-3", hourVal: "2",   gridArea: "9/2/10/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "2-3", hourVal: "2",   gridArea: "9/3/10/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "2-3", hourVal: "2",   gridArea: "9/4/10/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "2-3", hourVal: "2",   gridArea: "9/5/10/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "2-3", hourVal: "2",   gridArea: "9/6/10/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "2-3", hourVal: "2",   gridArea: "9/7/10/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "2-3", hourVal: "2",   gridArea: "9/8/10/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "3-4", hourVal: "3",   gridArea: "10/2/11/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "3-4", hourVal: "3",   gridArea: "10/3/11/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "3-4", hourVal: "3",   gridArea: "10/4/11/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "3-4", hourVal: "3",   gridArea: "10/5/11/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "3-4", hourVal: "3",   gridArea: "10/6/11/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "3-4", hourVal: "3",   gridArea: "10/7/11/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "3-4", hourVal: "3",   gridArea: "10/8/11/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "4-5", hourVal: "4",   gridArea: "11/2/12/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "4-5", hourVal: "4",   gridArea: "11/3/12/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "4-5", hourVal: "4",   gridArea: "11/4/12/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "4-5", hourVal: "4",   gridArea: "11/5/12/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "4-5", hourVal: "4",   gridArea: "11/6/12/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "4-5", hourVal: "4",   gridArea: "11/7/12/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "4-5", hourVal: "4",   gridArea: "11/8/12/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "5-6", hourVal: "5",   gridArea: "12/2/13/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "5-6", hourVal: "5",   gridArea: "12/3/13/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "5-6", hourVal: "5",   gridArea: "12/4/13/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "5-6", hourVal: "5",   gridArea: "12/5/13/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "5-6", hourVal: "5",   gridArea: "12/6/13/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "5-6", hourVal: "5",   gridArea: "12/7/13/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "5-6", hourVal: "5",   gridArea: "12/8/13/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "6-7", hourVal: "6",   gridArea: "13/2/14/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "6-7", hourVal: "6",   gridArea: "13/3/14/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "6-7", hourVal: "6",   gridArea: "13/4/14/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "6-7", hourVal: "6",   gridArea: "13/5/14/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "6-7", hourVal: "6",   gridArea: "13/6/14/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "6-7", hourVal: "6",   gridArea: "13/7/14/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "6-7", hourVal: "6",   gridArea: "13/8/14/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
  {selected: false,   day: "شن",   dayVal: "1",   hour: "7-8", hourVal: "7",   gridArea: "14/2/15/3"},
  {selected: false,   day: "یک",   dayVal: "2",   hour: "7-8", hourVal: "7",   gridArea: "14/3/15/4"},
  {selected: false,   day: "دو",   dayVal: "3",   hour: "7-8", hourVal: "7",   gridArea: "14/4/15/5"},
  {selected: false,   day: "سه",   dayVal: "4",   hour: "7-8", hourVal: "7",   gridArea: "14/5/15/6"},
  {selected: false,   day: "چهار", dayVal: "5",   hour: "7-8", hourVal: "7",   gridArea: "14/6/15/7"},
  {selected: false,   day: "پنج",  dayVal: "6",   hour: "7-8", hourVal: "7",   gridArea: "14/7/15/8"},
  {selected: false,   day: "جم",   dayVal: "7",   hour: "7-8", hourVal: "7",   gridArea: "14/8/15/9"},
];
